//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseShare.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.MoneyTransactions = new HashSet<MoneyTransaction>();
            this.Owes = new HashSet<Owe>();
            this.Payments = new HashSet<Payment>();
            this.Purchases = new HashSet<Purchase>();
            this.ShareEntities = new HashSet<ShareEntity>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MoneyTransaction> MoneyTransactions { get; set; }
        public virtual ICollection<Owe> Owes { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual ICollection<ShareEntity> ShareEntities { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
