//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseShare.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseShareEntities : DbContext
    {
        public HouseShareEntities()
            : base("name=HouseShareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<MoneyTransaction> MoneyTransactions { get; set; }
        public virtual DbSet<Owe> Owes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<ShareEntity> ShareEntities { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<ShareEntityDate> ShareEntityDates { get; set; }
        public virtual DbSet<PurchaseShare> PurchaseShares { get; set; }
    }
}
