//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseShare.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyTransaction
    {
        public int Id { get; set; }
        public System.DateTime TxDate { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
    
        public virtual House House { get; set; }
        public virtual Owe Owe { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Purchase Purchase { get; set; }
        public virtual ShareEntity FromEntity { get; set; }
        public virtual ShareEntity ToEntity { get; set; }
        public virtual Owe PaymentOwe { get; set; }
    }
}
