//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseShare.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseShare
    {
        public int Id { get; set; }
        public decimal Shares { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual ShareEntity ShareEntity { get; set; }
    }
}
