//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseShare.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareEntity
    {
        public ShareEntity()
        {
            this.Owes = new HashSet<Owe>();
            this.Owes1 = new HashSet<Owe>();
            this.Payments = new HashSet<Payment>();
            this.Payments1 = new HashSet<Payment>();
            this.Purchases = new HashSet<Purchase>();
            this.MoneyTransactions = new HashSet<MoneyTransaction>();
            this.MoneyTransactions1 = new HashSet<MoneyTransaction>();
            this.ShareEntityDates = new HashSet<ShareEntityDate>();
            this.PurchaseShares = new HashSet<PurchaseShare>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual House House { get; set; }
        public virtual ICollection<Owe> Owes { get; set; }
        public virtual ICollection<Owe> Owes1 { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Payment> Payments1 { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual ICollection<MoneyTransaction> MoneyTransactions { get; set; }
        public virtual ICollection<MoneyTransaction> MoneyTransactions1 { get; set; }
        public virtual ICollection<ShareEntityDate> ShareEntityDates { get; set; }
        public virtual ICollection<PurchaseShare> PurchaseShares { get; set; }
    }
}
